{% set version = "2.1.8" %}

package:
  name: strec
  version: {{ version }}

source:
  url: https://github.com/usgs/strec/archive/{{ version }}.tar.gz
  sha256: 4911f65228fd791af13908749169ccf52e810216d5b4438847b58dd2b7a4028e

build:
  noarch: python
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - fiona
    - libcomcat
    - mapio
    - numpy
    - obspy
    - openpyxl
    - pandas
    - pyproj
    - shapely
    - xlrd
    - xlwt
    

test:

  imports:
    - strec

about:
  home: https://github.com/usgs/strec
  license: CC-PDDC
  summary: 'Determine the tectonic region of an earthquake (Subduction,Active,Volcanic,Stable)'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
