{% set version = "2.1.4" %}

package:
  name: strec
  version: {{ version }}

source:
  url: https://github.com/usgs/strec/archive/{{ version }}.tar.gz
  sha256: 2761f7f2f7f4d821da5649412624fa80f22480b224287c92ca9e6b36ad0a9ef5

build:
  noarch: python
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - fiona
    - libcomcat
    - mapio
    - numpy
    - obspy
    - openpyxl
    - pandas
    - pyproj
    - shapely
    - xlrd
    - xlwt
    

test:

  imports:
    - strec

about:
  home: https://github.com/usgs/strec
  license: Public Domain
  summary: 'Determine the tectonic region of an earthquake (Subduction,Active,Volcanic,Stable)'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
