{% set version = "2.1.6" %}

package:
  name: strec
  version: {{ version }}

source:
  url: https://github.com/usgs/strec/archive/{{ version }}.tar.gz
  sha256: 1a634494fa6fb61c50666a249acdb29135e9c42edfcd5d2ce83a0cc12669aa82

build:
  noarch: python
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python>=3.6
    - pip
  run:
    - python>=3.6
    - fiona
    - libcomcat
    - mapio
    - numpy
    - obspy
    - openpyxl
    - pandas
    - pyproj
    - shapely
    - xlrd
    - xlwt
    

test:

  imports:
    - strec

about:
  home: https://github.com/usgs/strec
  license: Public Domain
  summary: 'Determine the tectonic region of an earthquake (Subduction,Active,Volcanic,Stable)'
  license_family: Public Domain
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - mhearne-usgs
    - cbworden
    - emthompson-usgs
