# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ff8j7FsWkjj6YWxw6MLAuZ11GhsnkJsJ86/N7M1Tg8KdcYcbJ1a5C9/IfLBFoacqeZEtlB7/CAig9FH3sFi4ktnSQNHnBzWdmiPa2HRHrPFhmRp777gQye2kJ0AKiT0R1ZIY/iet73HlSsLfjNKoA+jx4oyyM7xo+7XQc9DNTQnR4VhYByfxeGbxSAr+Gg2YYp9kWl0tk5Fz1plbgus4vdpC8hOFGGa0UWT65BiBWwTDe7AsACng30ajvbGtQ/AGikmqkdaKW2dYCEqOqzFqNxYQuOhNZSaywQTi0dsQ/97Sg/ZfBhr0IcMdC/sz6lFsKOPmkAAlSSTF/UQHqe8e8uMoUW+5VDbG1DrQ5n9wn8btkcKhBhT2Y1UkMWzfcJElN3GPvjoHzl5+reomc/QGG/Uyae7cNLwyZ50lqVZ7spS+SktLjDhMaihf7ZF9FVXsU8kAJGkIZZBgp0G413hf+NytnWUSzu/OvElZNYsH/4lP+7xFXUCMZd9K3FTzWNZxO8zp+hdtReWi/HSoCFRIVO+0vSObDWMDtuVX3Ubfd+OSbBpRviDZ5g53axsXMjGHBFJGUTX5HNm2HkR7q6sv1XsCjjWHRpOGqybR3PCU3zO5PletL5ePrTpsLEmLLXOJ3dt7XQhTNVsg/22tqobhJ1xlsVHyPy3Jx2UuDUZrg94="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
