travis:
  secure:
    BINSTAR_TOKEN: ff8j7FsWkjj6YWxw6MLAuZ11GhsnkJsJ86/N7M1Tg8KdcYcbJ1a5C9/IfLBFoacqeZEtlB7/CAig9FH3sFi4ktnSQNHnBzWdmiPa2HRHrPFhmRp777gQye2kJ0AKiT0R1ZIY/iet73HlSsLfjNKoA+jx4oyyM7xo+7XQc9DNTQnR4VhYByfxeGbxSAr+Gg2YYp9kWl0tk5Fz1plbgus4vdpC8hOFGGa0UWT65BiBWwTDe7AsACng30ajvbGtQ/AGikmqkdaKW2dYCEqOqzFqNxYQuOhNZSaywQTi0dsQ/97Sg/ZfBhr0IcMdC/sz6lFsKOPmkAAlSSTF/UQHqe8e8uMoUW+5VDbG1DrQ5n9wn8btkcKhBhT2Y1UkMWzfcJElN3GPvjoHzl5+reomc/QGG/Uyae7cNLwyZ50lqVZ7spS+SktLjDhMaihf7ZF9FVXsU8kAJGkIZZBgp0G413hf+NytnWUSzu/OvElZNYsH/4lP+7xFXUCMZd9K3FTzWNZxO8zp+hdtReWi/HSoCFRIVO+0vSObDWMDtuVX3Ubfd+OSbBpRviDZ5g53axsXMjGHBFJGUTX5HNm2HkR7q6sv1XsCjjWHRpOGqybR3PCU3zO5PletL5ePrTpsLEmLLXOJ3dt7XQhTNVsg/22tqobhJ1xlsVHyPy3Jx2UuDUZrg94=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
