travis:
  secure:
    BINSTAR_TOKEN: rS+JtynIU0Q2olfLTDzK5aOa37bthg92r9RVVTeGSCEnvG+dDDJbAmrZIvnLgJEESfTwMyv/B1fCn6ubhx1rB37MZU+raWYQGv8ASoQR/qAbwyjGCoMxtLZalvvFiUENmnQCFNeoOL8vSS9tRNhcCgkrWNSUJbspytyprDuYIO7MwRAM0EsAG3PIIcg/RLSELInG7wYiyIeFXBuOUJFC9CR1A8ZW5mHWuDpkJCkyquQ02ycHPdiqc86TeT3xCTedUz0tFn5KNwT5ltSWV6E6rcX8RCQjdJJ6LNkvch1Oom66V5qTno8XUoMafZxPsoV4JvILjb4P/Vm4XjwGIZ0Wrv0eqnU6/g5TXD8eulTwetB6VeUWQ790DwY9bqSG3Ota0entmPVvS8eU6eUL4Arg1XAAa7v1IVKnqpbiflDydn+ii0ZhZiSGc2RKjQHMQxUOIoqKqEXmJ5tT4CzeJyLBlTVqTIifD9rv6T9U4ewrG3iQfISXK6rVJzr/POnYTPtKEH48G/x7uqAWacnm/+7T8gEt2c73GmwGqs4Nke5p54DfLinsyikV5UE1GwiXmXS3swAYW6AWbIy5Hv7VMK4ZfVjP08VsXUa0O2evyFSuvBRhc/qFdui0MdfkfSL8Ny++UH74327vrCQqmoW/fnp3/CVz2okPIWnE5zW1xGWxrAk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
